var vpzResearchCenter_data = [
    {
        "title":"Guinea Pig",
        "creator":"VPZ Research Center",
        "url":"https://web.archive.org/web/20190105203546/https://www.angelfire.com/moon2/petzzoo2",
        "desc":`
            (Editor's note: Sounds are currently missing, if someone has a copy please contribute them!)
        `,
        "filetype":"breedfile",
        "subtype":"catz",
        "imgSmall":"",
        "imgLarge":"files/vpz-research-center/catbreedz/wildz_catz/GuineaPig/GuineaPig.gif",
        "downloadLinks":
        {
            "Catz 1":"",
            "Dogz 1":"",
            "Petz II":"",
            "Petz 3":"",
            "Petz 4":"",
            "Petz 5":"",
            "Unibreed":"files/vpz-research-center/catbreedz/wildz_catz/GuineaPig/cavy.zip",
            "Petz II OW":"",
            "Petz 3 OW":"",
            "Petz 4 OW":"",
            "Petz 5 OW":"",
            "Unibreed OW":"",
            "Other":"",
        },
        "tags":""
    },
    {
        "title":"Hamsterz",
        "creator":"VPZ Research Center",
        "url":"https://web.archive.org/web/20190105203546/https://www.angelfire.com/moon2/petzzoo2",
        "desc":``,
        "filetype":"breedfile",
        "subtype":"catz",
        "imgSmall":"",
        "imgLarge":"files/vpz-research-center/catbreedz/wildz_catz/Hamsterz/hamster.gif",
        "downloadLinks":
        {
            "Catz 1":"",
            "Dogz 1":"",
            "Petz II":"",
            "Petz 3":"",
            "Petz 4":"",
            "Petz 5":"",
            "Unibreed":"files/vpz-research-center/catbreedz/wildz_catz/Hamsterz/hamster.zip",
            "Petz II OW":"",
            "Petz 3 OW":"",
            "Petz 4 OW":"",
            "Petz 5 OW":"",
            "Unibreed OW":"",
            "Other":"",
        },
        "tags":""
    },
    {
        "title":"Mice",
        "creator":"VPZ Research Center",
        "url":"https://web.archive.org/web/20190105203546/https://www.angelfire.com/moon2/petzzoo2",
        "desc":`
            (Editor's Note: This file has 3 variations: Marked, Fox/Tan, and Longhair. Each variation overwrites each other)`,
        "filetype":"breedfile",
        "subtype":"catz",
        "imgSmall":"",
        "imgLarge":"files/vpz-research-center/catbreedz/wildz_catz/Mice/mice.gif",
        "downloadLinks":
        {
            "Catz 1":"",
            "Dogz 1":"",
            "Petz II":"",
            "Petz 3":"",
            "Petz 4":"",
            "Petz 5":"",
            "Unibreed":"files/vpz-research-center/catbreedz/wildz_catz/Mice/mice.zip",
            "Petz II OW":"",
            "Petz 3 OW":"",
            "Petz 4 OW":"",
            "Petz 5 OW":"",
            "Unibreed OW":"",
            "Other":"",
        },
        "tags":""
    },
    {
        "title":"Ratz",
        "creator":"VPZ Research Center",
        "url":"https://web.archive.org/web/20190105203546/https://www.angelfire.com/moon2/petzzoo2",
        "desc":`
            (Editor's Note: This file has 2 variations: Standard and Rex. These variations overwrite each other)`,
        "filetype":"breedfile",
        "subtype":"catz",
        "imgSmall":"",
        "imgLarge":"files/vpz-research-center/catbreedz/wildz_catz/Ratz/ratz.gif",
        "downloadLinks":
        {
            "Catz 1":"",
            "Dogz 1":"",
            "Petz II":"",
            "Petz 3":"",
            "Petz 4":"",
            "Petz 5":"",
            "Unibreed":"files/vpz-research-center/catbreedz/wildz_catz/Ratz/ratz.zip",
            "Petz II OW":"",
            "Petz 3 OW":"",
            "Petz 4 OW":"",
            "Petz 5 OW":"",
            "Unibreed OW":"",
            "Other":"",
        },
        "tags":""
    },
    {
        "title":"Gouldian Finch",
        "creator":"VPZ Research Center",
        "url":"https://web.archive.org/web/20190105203546/https://www.angelfire.com/moon2/petzzoo2",
        "desc":``,
        "filetype":"breedfile",
        "subtype":"catz",
        "imgSmall":"",
        "imgLarge":"files/vpz-research-center/catbreedz/wildz_catz/GouldianFinch/gfinch.gif",
        "downloadLinks":
        {
            "Catz 1":"",
            "Dogz 1":"",
            "Petz II":"",
            "Petz 3":"",
            "Petz 4":"",
            "Petz 5":"",
            "Unibreed":"files/vpz-research-center/catbreedz/wildz_catz/GouldianFinch/gfin.zip",
            "Petz II OW":"",
            "Petz 3 OW":"",
            "Petz 4 OW":"",
            "Petz 5 OW":"",
            "Unibreed OW":"",
            "Other":"",
        },
        "tags":""
    },
    {
        "title":"Parrot",
        "creator":"VPZ Research Center",
        "url":"https://web.archive.org/web/20190105203546/https://www.angelfire.com/moon2/petzzoo2",
        "desc":``,
        "filetype":"breedfile",
        "subtype":"catz",
        "imgSmall":"",
        "imgLarge":"files/vpz-research-center/catbreedz/wildz_catz/Parrot/parrot.gif",
        "downloadLinks":
        {
            "Catz 1":"",
            "Dogz 1":"",
            "Petz II":"",
            "Petz 3":"",
            "Petz 4":"",
            "Petz 5":"",
            "Unibreed":"files/vpz-research-center/catbreedz/wildz_catz/Parrot/parrot.zip",
            "Petz II OW":"",
            "Petz 3 OW":"",
            "Petz 4 OW":"",
            "Petz 5 OW":"",
            "Unibreed OW":"",
            "Other":"",
        },
        "tags":""
    },
    {
        "title":"Raven",
        "creator":"VPZ Research Center",
        "url":"https://web.archive.org/web/20190105203546/https://www.angelfire.com/moon2/petzzoo2",
        "desc":``,
        "filetype":"breedfile",
        "subtype":"catz",
        "imgSmall":"",
        "imgLarge":"files/vpz-research-center/catbreedz/wildz_catz/Raven/raven.gif",
        "downloadLinks":
        {
            "Catz 1":"",
            "Dogz 1":"",
            "Petz II":"",
            "Petz 3":"",
            "Petz 4":"",
            "Petz 5":"",
            "Unibreed":"files/vpz-research-center/catbreedz/wildz_catz/Raven/raven.zip",
            "Petz II OW":"",
            "Petz 3 OW":"",
            "Petz 4 OW":"",
            "Petz 5 OW":"",
            "Unibreed OW":"",
            "Other":"",
        },
        "tags":""
    },
    {
        "title":"Society Finch",
        "creator":"VPZ Research Center",
        "url":"https://web.archive.org/web/20190105203546/https://www.angelfire.com/moon2/petzzoo2",
        "desc":``,
        "filetype":"breedfile",
        "subtype":"catz",
        "imgSmall":"",
        "imgLarge":"files/vpz-research-center/catbreedz/wildz_catz/SocietyFinch/sFinch.gif",
        "downloadLinks":
        {
            "Catz 1":"",
            "Dogz 1":"",
            "Petz II":"",
            "Petz 3":"",
            "Petz 4":"",
            "Petz 5":"",
            "Unibreed":"files/vpz-research-center/catbreedz/wildz_catz/SocietyFinch/sfin.zip",
            "Petz II OW":"",
            "Petz 3 OW":"",
            "Petz 4 OW":"",
            "Petz 5 OW":"",
            "Unibreed OW":"",
            "Other":"",
        },
        "tags":""
    },
    {
        "title":"Llamaz",
        "creator":"VPZ Research Center",
        "url":"https://web.archive.org/web/20190105203546/https://www.angelfire.com/moon2/petzzoo2",
        "desc":``,
        "filetype":"breedfile",
        "subtype":"catz",
        "imgSmall":"",
        "imgLarge":"files/vpz-research-center/catbreedz/wildz_catz/Llamaz/llama.gif",
        "downloadLinks":
        {
            "Catz 1":"",
            "Dogz 1":"",
            "Petz II":"",
            "Petz 3":"",
            "Petz 4":"",
            "Petz 5":"",
            "Unibreed":"files/vpz-research-center/catbreedz/wildz_catz/Llamaz/llama.zip",
            "Petz II OW":"",
            "Petz 3 OW":"",
            "Petz 4 OW":"",
            "Petz 5 OW":"",
            "Unibreed OW":"",
            "Other":"",
        },
        "tags":""
    },
    {
        "title":"Shetland Pony",
        "creator":"VPZ Research Center",
        "url":"https://web.archive.org/web/20190105203546/https://www.angelfire.com/moon2/petzzoo2",
        "desc":`(Editor's note: Sounds are currently missing, if someone has a copy please contribute them!)`,
        "filetype":"breedfile",
        "subtype":"catz",
        "imgSmall":"",
        "imgLarge":"files/vpz-research-center/catbreedz/wildz_catz/ShetlandPony/pony.gif",
        "downloadLinks":
        {
            "Catz 1":"",
            "Dogz 1":"",
            "Petz II":"",
            "Petz 3":"",
            "Petz 4":"",
            "Petz 5":"",
            "Unibreed":"files/vpz-research-center/catbreedz/wildz_catz/ShetlandPony/pony.zip",
            "Petz II OW":"",
            "Petz 3 OW":"",
            "Petz 4 OW":"",
            "Petz 5 OW":"",
            "Unibreed OW":"",
            "Other":"",
        },
        "tags":""
    },
    {
        "title":"Arctic Hare",
        "creator":"VPZ Research Center",
        "url":"https://web.archive.org/web/20190105203546/https://www.angelfire.com/moon2/petzzoo2",
        "desc":``,
        "filetype":"breedfile",
        "subtype":"catz",
        "imgSmall":"",
        "imgLarge":"files/vpz-research-center/catbreedz/wildz_catz/ArcticHare/hare.gif",
        "downloadLinks":
        {
            "Catz 1":"",
            "Dogz 1":"",
            "Petz II":"",
            "Petz 3":"",
            "Petz 4":"",
            "Petz 5":"",
            "Unibreed":"files/vpz-research-center/catbreedz/wildz_catz/ArcticHare/arctichare.zip",
            "Petz II OW":"",
            "Petz 3 OW":"",
            "Petz 4 OW":"",
            "Petz 5 OW":"",
            "Unibreed OW":"",
            "Other":"",
        },
        "tags":""
    },
    {
        "title":"Ferretz",
        "creator":"VPZ Research Center",
        "url":"https://web.archive.org/web/20190105203546/https://www.angelfire.com/moon2/petzzoo2",
        "desc":``,
        "filetype":"breedfile",
        "subtype":"catz",
        "imgSmall":"",
        "imgLarge":"files/vpz-research-center/catbreedz/wildz_catz/Ferretz/ferretz.gif",
        "downloadLinks":
        {
            "Catz 1":"",
            "Dogz 1":"",
            "Petz II":"",
            "Petz 3":"",
            "Petz 4":"",
            "Petz 5":"",
            "Unibreed":"files/vpz-research-center/catbreedz/wildz_catz/Ferretz/fertz.zip",
            "Petz II OW":"",
            "Petz 3 OW":"",
            "Petz 4 OW":"",
            "Petz 5 OW":"",
            "Unibreed OW":"",
            "Other":"",
        },
        "tags":""
    },
    {
        "title":"Pygmy Hedgehog",
        "creator":"VPZ Research Center",
        "url":"https://web.archive.org/web/20190105203546/https://www.angelfire.com/moon2/petzzoo2",
        "desc":``,
        "filetype":"breedfile",
        "subtype":"catz",
        "imgSmall":"",
        "imgLarge":"files/vpz-research-center/catbreedz/wildz_catz/PygmyHedgehog/hedgehog.gif",
        "downloadLinks":
        {
            "Catz 1":"",
            "Dogz 1":"",
            "Petz II":"",
            "Petz 3":"",
            "Petz 4":"",
            "Petz 5":"",
            "Unibreed":"files/vpz-research-center/catbreedz/wildz_catz/PygmyHedgehog/hedgehog.zip",
            "Petz II OW":"",
            "Petz 3 OW":"",
            "Petz 4 OW":"",
            "Petz 5 OW":"",
            "Unibreed OW":"",
            "Other":"",
        },
        "tags":""
    },
    {
        "title":"Kinkajou",
        "creator":"VPZ Research Center",
        "url":"https://web.archive.org/web/20190105203546/https://www.angelfire.com/moon2/petzzoo2",
        "desc":``,
        "filetype":"breedfile",
        "subtype":"catz",
        "imgSmall":"",
        "imgLarge":"files/vpz-research-center/catbreedz/wildz_catz/Kinkajou/kinkajou.gif",
        "downloadLinks":
        {
            "Catz 1":"",
            "Dogz 1":"",
            "Petz II":"",
            "Petz 3":"",
            "Petz 4":"",
            "Petz 5":"",
            "Unibreed":"files/vpz-research-center/catbreedz/wildz_catz/Kinkajou/kink.zip",
            "Petz II OW":"",
            "Petz 3 OW":"",
            "Petz 4 OW":"",
            "Petz 5 OW":"",
            "Unibreed OW":"",
            "Other":"",
        },
        "tags":""
    },
    {
        "title":"Ring-Tailed Lemur",
        "creator":"VPZ Research Center",
        "url":"https://web.archive.org/web/20190105203546/https://www.angelfire.com/moon2/petzzoo2",
        "desc":``,
        "filetype":"breedfile",
        "subtype":"catz",
        "imgSmall":"",
        "imgLarge":"files/vpz-research-center/catbreedz/wildz_catz/RingTailedLemur/lemur.gif",
        "downloadLinks":
        {
            "Catz 1":"",
            "Dogz 1":"",
            "Petz II":"",
            "Petz 3":"",
            "Petz 4":"",
            "Petz 5":"",
            "Unibreed":"files/vpz-research-center/catbreedz/wildz_catz/RingTailedLemur/lemur.zip",
            "Petz II OW":"",
            "Petz 3 OW":"",
            "Petz 4 OW":"",
            "Petz 5 OW":"",
            "Unibreed OW":"",
            "Other":"",
        },
        "tags":""
    },
    {
        "title":"Striped Skunk",
        "creator":"VPZ Research Center",
        "url":"https://web.archive.org/web/20190105203546/https://www.angelfire.com/moon2/petzzoo2",
        "desc":``,
        "filetype":"breedfile",
        "subtype":"catz",
        "imgSmall":"",
        "imgLarge":"files/vpz-research-center/catbreedz/wildz_catz/StripedSkunk/skunk.gif",
        "downloadLinks":
        {
            "Catz 1":"",
            "Dogz 1":"",
            "Petz II":"",
            "Petz 3":"",
            "Petz 4":"",
            "Petz 5":"",
            "Unibreed":"files/vpz-research-center/catbreedz/wildz_catz/StripedSkunk/skunknow.zip",
            "Petz II OW":"",
            "Petz 3 OW":"",
            "Petz 4 OW":"",
            "Petz 5 OW":"",
            "Unibreed OW":"",
            "Other":"",
        },
        "tags":""
    },
    {
        "title":"Sugar Glider",
        "creator":"VPZ Research Center",
        "url":"https://web.archive.org/web/20190105203546/https://www.angelfire.com/moon2/petzzoo2",
        "desc":``,
        "filetype":"breedfile",
        "subtype":"catz",
        "imgSmall":"",
        "imgLarge":"files/vpz-research-center/catbreedz/wildz_catz/SugarGlider/glider.gif",
        "downloadLinks":
        {
            "Catz 1":"",
            "Dogz 1":"",
            "Petz II":"",
            "Petz 3":"",
            "Petz 4":"",
            "Petz 5":"",
            "Unibreed":"files/vpz-research-center/catbreedz/wildz_catz/SugarGlider/glider.zip",
            "Petz II OW":"",
            "Petz 3 OW":"",
            "Petz 4 OW":"",
            "Petz 5 OW":"",
            "Unibreed OW":"",
            "Other":"",
        },
        "tags":""
    },
    {
        "title":"Virginia Opossum",
        "creator":"VPZ Research Center",
        "url":"https://web.archive.org/web/20190105203546/https://www.angelfire.com/moon2/petzzoo2",
        "desc":``,
        "filetype":"breedfile",
        "subtype":"catz",
        "imgSmall":"",
        "imgLarge":"files/vpz-research-center/catbreedz/wildz_catz/VirginiaOpossum/possum.gif",
        "downloadLinks":
        {
            "Catz 1":"",
            "Dogz 1":"",
            "Petz II":"",
            "Petz 3":"",
            "Petz 4":"",
            "Petz 5":"",
            "Unibreed":"files/vpz-research-center/catbreedz/wildz_catz/VirginiaOpossum/possum.zip",
            "Petz II OW":"",
            "Petz 3 OW":"",
            "Petz 4 OW":"",
            "Petz 5 OW":"",
            "Unibreed OW":"",
            "Other":"",
        },
        "tags":""
    },
    {
        "title":"Shelter Dogz",
        "creator":"VPZ Research Center",
        "url":"https://web.archive.org/web/20190105203546/https://www.angelfire.com/moon2/petzzoo2",
        "desc":`
            Every year, millions of dogs are euthanized in shelters in the USA, simply because homes are not available.  These dogz have done no wrong but are simply the result of overpopulation, lack of spaying/neutering, and intentional and unintentional overbreeding.  While they have no "papers," shelter dogs make wonderful pets, as well as doing rescue work, police work, and therapy work.  Movies and TV frequently use dogs from shelters as their "stars," as many are very intelligent and eager to please.  Shelter dogs can be purebred or mixed, and are the best place to begin any search for a canine companion.
            <br/><br/>
            In this file, literally hundreds of billions of possibilities exist, as in real life.  (You can see some examples of these variations here.) I recommend you do not search for a specific dog but rather take whatever comes to you from the Adoption Center, like the puppy you found by the road or the one that followed you home...
            <br/><br/>
            Pssst... if you like these, check out Nova's Mixed Breed for Dogz or my Moggiez for catz!`,
        "filetype":"breedfile",
        "subtype":"dogz",
        "imgSmall":"",
        "imgLarge":"shelterdogz.gif",
        "downloadLinks":
        {
            "catz1":"",
            "dogz1":"",
            "p2":"",
            "p3":"",
            "p4":"",
            "p5":"",
            "unibreed":"",
            "other":"",
            "p2ow":"",
            "p3ow":"",
            "p4ow":"",
            "p5ow":"",
            "unibreedow":"",
            "other":"",
        },
        "tags":""
    }
]

export { vpzResearchCenter_data };